default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgresql://localhost/always200_development?user=postgres&password=123456

test:
  <<: *default
  database: always200_test

production:
  <<: *default
  database: always200_production
  username: always200
  password: <%= ENV['LUCKY_MAN_DATABASE_PASSWORD'] %>
